# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'USERS-LIST' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USERS-LIST

pod 'Realm'

pod 'Alamofire'
pod 'AlamofireImage'

pod 'TOCropViewController'

end
